AllCops:
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 119

MethodLength:
  Max: 40

ClassLength:
  Max: 200

BlockLength:
  Max: 40

ModuleLength:
  Enabled: false

NumericLiterals:
  Enabled: false

RedundantSelf:
  Enabled: false
