# frozen_string_literal: true

module Robottelo
  module Reporter
    TEST_ATTRIBUTE_ID = :pid
    TESTCASE_PROPERTIES_MAPPING = {
      pid: 'polarion-testcase-id'
    }.freeze
  end
  PROPERTY_PREFIX = 'polarion'
  PROPERTY_PREFIX_CUSTOM = 'polarion-custom'
  ENV_POLARION_PROPERTIES = 'POLARION_PROPERTIES'
  ENV_POLARION_CUSTOM_PROPERTIES = 'POLARION_CUSTOM_PROPERTIES'
  ENV_ROBOTTELO_REPORT_NAME = 'ROBOTTELO_REPORT_NAME'
  ENV_ROBOTTELO_REPORT_PATH = 'ROBOTTELO_REPORT_PATH'
  ENV_CI_REPORTS = 'CI_REPORTS'
end
